name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: make test
      run: make test CC=${{ matrix.cc }}
  memtest:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install valgrind
      run: sudo apt install -y valgrind
    - name: make memtest
      run: make memtest CC=${{ matrix.cc }}
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install clang-tidy
      run: sudo apt install -y clang-tidy
    - name: make lint
      run: make lint
  check-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install clang-format
      run: sudo apt install -y clang-format
    - name: make check-format
      run: make check-format
