name: Demo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install wasi-sdk
      run: |
        wget --no-verbose 'https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz'
        tar xf wasi-sdk-12.0-linux.tar.gz
        rm wasi-sdk-12.0-linux.tar.gz
        echo "$(pwd)/wasi-sdk-12.0/bin" >> $GITHUB_PATH
    - name: Build
      run: make demo
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: demo
        single-commit: true
